version: "3"
services:
    web:
        container_name: crud_vozy
        restart: always
        build: .
        environment:
            - MONGO_DB_URI=${MONGO_DB_URI}
        ports:
            - "5000:3000"
        links:
            - mongo
        volumes:
            - .:usr/src/app
    mongo:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"
