version: "3"
services:
    web:
        container_name: crud_vozy
        restart: always
        build: .
        # environment:
        #     - MONGO_DB_URI=mongodb://mongo:27017/crud
        ports:
            - "5000:3001"
        links:
            - mongo

    mongo:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"
